language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: OIyOrs68MLmXbZKhnQK1qO5PZcMbgPdqhGGM4MCBYWLthP0FhMoB4b5cWQ+e4TRa8spuZ/phHqhUDPlWkKefK/CIQzads3E03sexXxDPSopYkhgpPYT7vqRCcRqPPc+4aj1BtlzDR1q0+COe1qTO+kYk2IhSIvW8F1STISnh6gpXqZd+HJt4fLYtMKPX+boP7P8dkcGATJmP2Nxv61MsehjvFSea2k6uts3mjlOSkzgr4QYiW0IZ9PyX+rtfQrv3Xy4+g935f9NbyMSaP1KW5G8AI5W83m0kNeFJhN2oqs5adTKI8QHu9WoIn07+qjsdW/JxgsO2c1ZEq8BOtv0JOTRs0yPMPBZqSxdTW9rN8fesl4VOg8p/5+w4t1WzioePcB2CSFjVl/6Oog7wYJhpxWGB7pJomd0NggRqAOIm+vYyEN3AoWfPwGiA0WRoW+5HpXynEG5ggPWfoNLHXxHfGRAjuseIqMbSF9HyEwYXjnKDUkKHdrw8AE07MVVaHgvViQFEO2IVpC1cVW4k8SaXQLIsdRzPWGp2kCYRx3MSfQRlvrINKAdN6LJiDY4oU1VgXTlVTZsLJ0K0lvuAF0VRhNRCoVslSG5z8W/Ue6l2uF+y3Fx7OKpofKpJrDqcO3lCPEMe37nZQgVCfvf7e4wThrftY40sXdeTwrXH0CvsigY=
